# Generated by Django 2.0.7 on 2018-08-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='taskstatus',
            field=models.BooleanField(default=False),
        ),
    ]
